wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.12
    cli_version: 0.22.2
    framework: huggingface
    huggingface_version: 4.57.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1761371724
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 71
      - 84
      - 95
      - 98
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 71
      - 84
      - 95
      - 98
      3:
      - 4
      - 7
      - 13
      - 19
      - 42
      - 62
      - 66
      4: 3.12.12
      5: 0.22.2
      6: 4.57.1
      9:
        1: transformers_trainer
      13: linux-x86_64
    e:
      zvb1gacjei7d8d006x5358ucokbllp9c:
        os: Linux-5.15.0-139-generic-x86_64-with-glibc2.35
        python: CPython 3.12.12
        started_at: '2025-10-25T05:55:24.613718Z'
        args:
        - --config
        - config/DPO_config.yaml
        program: /root/HFRL/SFT_DPO/DPO.py
        code_path: DPO.py
        code_path_local: DPO.py
        git:
          remote_url: https://github.com/DopeorNope-Lee/Easy_DPO.git
          commit: 8751442fb8803d07ea6125d6916887ce936235db
        root: /root/HFRL/SFT_DPO
        host: d2b1fdbf9813
        executable: /root/miniconda3/envs/LLM/bin/python
        cpu_count: 64
        cpu_count_logical: 128
        gpu_type: NVIDIA H200 NVL
        gpu_count: 1
        disk:
          /:
            total: '942910771200'
            used: '142691131392'
        memory:
          total: '540689866752'
        gpu_nvidia:
        - name: NVIDIA H200 NVL
          memory_total: '150754820096'
          cuda_cores: 16896
          architecture: Hopper
          uuid: GPU-2c616e93-dc72-5c9d-4554-88192229c454
        cuda_version: '12.8'
        writer_id: zvb1gacjei7d8d006x5358ucokbllp9c
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/rewards/rejected
      5: 1
      6:
      - 1
    - 1: train/rewards/margins
      5: 1
      6:
      - 1
    - 1: train/logits/rejected
      5: 1
      6:
      - 1
    - 1: train/logps/rejected
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/rewards/chosen
      5: 1
      6:
      - 1
    - 1: train/rewards/accuracies
      5: 1
      6:
      - 1
    - 1: train/logps/chosen
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/logits/chosen
      5: 1
      6:
      - 1
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/rewards/chosen
      5: 1
      6:
      - 1
    - 1: eval/rewards/accuracies
      5: 1
      6:
      - 1
    - 1: eval/logits/rejected
      5: 1
      6:
      - 1
    - 1: eval/rewards/margins
      5: 1
      6:
      - 1
    - 1: eval/logps/rejected
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/logps/chosen
      5: 1
      6:
      - 1
    - 1: eval/logits/chosen
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: eval/rewards/rejected
      5: 1
      6:
      - 1
peft_config:
  desc: null
  value:
    default:
      task_type: CAUSAL_LM
      peft_type: LORA
      auto_mapping: null
      base_model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
      revision: null
      inference_mode: false
      r: 32
      target_modules:
      - o_proj
      - k_proj
      - v_proj
      - gate_proj
      - up_proj
      - q_proj
      - down_proj
      exclude_modules: null
      lora_alpha: 16
      lora_dropout: 0.05
      fan_in_fan_out: false
      bias: none
      use_rslora: false
      modules_to_save: null
      init_lora_weights: true
      layers_to_transform: null
      layers_pattern: null
      rank_pattern: {}
      alpha_pattern: {}
      megatron_config: null
      megatron_core: megatron.core
      trainable_token_indices: null
      loftq_config: {}
      eva_config: null
      corda_config: null
      use_dora: false
      use_qalora: false
      qalora_group_size: 16
      layer_replication: null
      runtime_config:
        ephemeral_gpu_offload: false
      lora_bias: false
      target_parameters: null
vocab_size:
  desc: null
  value: 128256
max_position_embeddings:
  desc: null
  value: 131072
hidden_size:
  desc: null
  value: 4096
intermediate_size:
  desc: null
  value: 14336
num_hidden_layers:
  desc: null
  value: 32
num_attention_heads:
  desc: null
  value: 32
num_key_value_heads:
  desc: null
  value: 8
hidden_act:
  desc: null
  value: silu
initializer_range:
  desc: null
  value: 0.02
rms_norm_eps:
  desc: null
  value: 1.0e-05
pretraining_tp:
  desc: null
  value: 1
use_cache:
  desc: null
  value: false
rope_theta:
  desc: null
  value: 500000.0
rope_scaling:
  desc: null
  value:
    factor: 8.0
    low_freq_factor: 1.0
    high_freq_factor: 4.0
    original_max_position_embeddings: 8192
    rope_type: llama3
attention_bias:
  desc: null
  value: false
attention_dropout:
  desc: null
  value: 0.0
mlp_bias:
  desc: null
  value: false
head_dim:
  desc: null
  value: 128
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
dtype:
  desc: null
  value: bfloat16
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: false
chunk_size_feed_forward:
  desc: null
  value: 0
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - LlamaForCausalLM
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: 128000
pad_token_id:
  desc: null
  value: 128009
eos_token_id:
  desc: null
  value: 128009
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
max_length:
  desc: null
  value: 1024
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
_name_or_path:
  desc: null
  value: meta-llama/Meta-Llama-3.1-8B-Instruct
transformers_version:
  desc: null
  value: 4.57.1
model_type:
  desc: null
  value: llama
tf_legacy_loss:
  desc: null
  value: false
use_bfloat16:
  desc: null
  value: false
quantization_config:
  desc: null
  value:
    quant_method: BITS_AND_BYTES
    _load_in_8bit: false
    _load_in_4bit: true
    llm_int8_threshold: 6.0
    llm_int8_skip_modules: null
    llm_int8_enable_fp32_cpu_offload: false
    llm_int8_has_fp16_weight: false
    bnb_4bit_quant_type: nf4
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: bfloat16
    bnb_4bit_quant_storage: uint8
    load_in_4bit: true
    load_in_8bit: false
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ./results/dpo-test
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
eval_strategy:
  desc: null
  value: steps
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 4
per_device_eval_batch_size:
  desc: null
  value: 4
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 2
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
torch_empty_cache_steps:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 5.0e-07
weight_decay:
  desc: null
  value: 0.01
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 0.5
num_train_epochs:
  desc: null
  value: 2
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: cosine_with_restarts
lr_scheduler_kwargs:
  desc: null
  value:
    num_cycles: 3
warmup_ratio:
  desc: null
  value: 0.06
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: ./results/dpo-test/runs/Oct25_14-54-48_d2b1fdbf9813
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 100
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: true
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
restore_callback_states_from_checkpoint:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
bf16:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: true
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 500
dataloader_num_workers:
  desc: null
  value: 4
dataloader_prefetch_factor:
  desc: null
  value: null
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: dpo-test
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: false
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_v2: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
accelerator_config:
  desc: null
  value:
    split_batches: false
    dispatch_batches: null
    even_batches: true
    use_seedable_sampler: true
    non_blocking: false
    gradient_accumulation_kwargs: null
parallelism_config:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch_fused
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
project:
  desc: null
  value: huggingface
trackio_space_id:
  desc: null
  value: trackio
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
dataloader_persistent_workers:
  desc: null
  value: false
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: null
hub_always_push:
  desc: null
  value: false
hub_revision:
  desc: null
  value: null
gradient_checkpointing:
  desc: null
  value: true
gradient_checkpointing_kwargs:
  desc: null
  value:
    use_reentrant: true
include_inputs_for_metrics:
  desc: null
  value: false
include_for_metrics:
  desc: null
  value: []
eval_do_concat_batches:
  desc: null
  value: true
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
include_tokens_per_second:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: 'no'
neftune_noise_alpha:
  desc: null
  value: null
optim_target_modules:
  desc: null
  value: null
batch_eval_metrics:
  desc: null
  value: false
eval_on_start:
  desc: null
  value: false
use_liger_kernel:
  desc: null
  value: false
liger_kernel_config:
  desc: null
  value: null
eval_use_gather_object:
  desc: null
  value: false
average_tokens_across_devices:
  desc: null
  value: true
model_init_kwargs:
  desc: null
  value: null
ref_model_init_kwargs:
  desc: null
  value: null
model_adapter_name:
  desc: null
  value: null
ref_adapter_name:
  desc: null
  value: null
force_use_ref_model:
  desc: null
  value: false
disable_dropout:
  desc: null
  value: true
use_logits_to_keep:
  desc: null
  value: false
dataset_num_proc:
  desc: null
  value: null
pad_token:
  desc: null
  value: <PAD_TOKEN>
label_pad_token_id:
  desc: null
  value: -100
max_prompt_length:
  desc: null
  value: 1024
max_completion_length:
  desc: null
  value: null
truncation_mode:
  desc: null
  value: keep_end
padding_free:
  desc: null
  value: true
precompute_ref_log_probs:
  desc: null
  value: false
precompute_ref_batch_size:
  desc: null
  value: null
tools:
  desc: null
  value: null
loss_type:
  desc: null
  value: apo_zero
use_liger_loss:
  desc: null
  value: false
base_model_attribute_name:
  desc: null
  value: model
beta:
  desc: null
  value: 0.1
f_divergence_type:
  desc: null
  value: reverse_kl
f_alpha_divergence_coef:
  desc: null
  value: 1.0
reference_free:
  desc: null
  value: false
label_smoothing:
  desc: null
  value: 0.0
use_weighting:
  desc: null
  value: false
rpo_alpha:
  desc: null
  value: null
ld_alpha:
  desc: null
  value: null
discopop_tau:
  desc: null
  value: 0.05
loss_weights:
  desc: null
  value: null
sync_ref_model:
  desc: null
  value: false
ref_model_mixup_alpha:
  desc: null
  value: 0.6
ref_model_sync_steps:
  desc: null
  value: 512
generate_during_eval:
  desc: null
  value: false
padding_value:
  desc: null
  value: null
model/num_parameters:
  desc: null
  value: 8114147328
