_wandb:
    value:
        cli_version: 0.23.0
        e:
            cxsaqwm478c15fqa3qg0bnsztcvo4jrw:
                args:
                    - --config
                    - config/DPO_config.yaml
                codePath: SurvLLM/DPO.py
                codePathLocal: DPO.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3935709487104"
                        used: "1624070647808"
                email: hcssk2800@gmail.com
                executable: /root/anaconda3/envs/RLHF/bin/python
                git:
                    commit: a48c144783447ac6308c85f90ff3fa995ee4c6b2
                    remote: https://github.com/HollyRiver/HFRL.git
                gpu: NVIDIA H200 NVL
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200 NVL
                      uuid: GPU-d0563410-d1d7-f334-1100-0b3a28db8bd2
                host: 1e2f4b7e9494
                memory:
                    total: "1622974427136"
                os: Linux-6.14.0-35-generic-x86_64-with-glibc2.35
                program: /root/HFRL/SurvLLM/DPO.py
                python: CPython 3.12.12
                root: /root/HFRL/SurvLLM
                startedAt: "2025-11-19T07:02:58.135572Z"
                writerId: cxsaqwm478c15fqa3qg0bnsztcvo4jrw
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 84
                - 95
                - 98
            "4": 3.12.12
            "5": 0.23.0
            "6": 4.57.1
            "12": 0.23.0
            "13": linux-x86_64
